# TODO(riyamehta): describe this package.

go_library(
  name = "tls_config_store",
  srcs = [tls_config_store.go],
  deps = []
)


go_library(
  name = "remote_signer",
  srcs = [remote_signer.go],
  deps = []
)


go_library(
  name = "cert_verifier",
  srcs = [cert_verifier.go],
  deps = []
)
