//
//
// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: example/proto/echo.proto

package echo_go_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EchoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoRequest) Reset() {
	*x = EchoRequest{}
	mi := &file_example_proto_echo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRequest) ProtoMessage() {}

func (x *EchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_echo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRequest.ProtoReflect.Descriptor instead.
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return file_example_proto_echo_proto_rawDescGZIP(), []int{0}
}

func (x *EchoRequest) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type EchoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoResponse) Reset() {
	*x = EchoResponse{}
	mi := &file_example_proto_echo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoResponse) ProtoMessage() {}

func (x *EchoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_echo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoResponse.ProtoReflect.Descriptor instead.
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return file_example_proto_echo_proto_rawDescGZIP(), []int{1}
}

func (x *EchoResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_example_proto_echo_proto protoreflect.FileDescriptor

const file_example_proto_echo_proto_rawDesc = "" +
	"\n" +
	"\x18example/proto/echo.proto\x12\x13s2av2.example.proto\"\x1f\n" +
	"\vEchoRequest\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\" \n" +
	"\fEchoResponse\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg2U\n" +
	"\x04Echo\x12M\n" +
	"\x04Echo\x12 .s2av2.example.proto.EchoRequest\x1a!.s2av2.example.proto.EchoResponse\"\x00B3Z1github.com/google/s2a/example/proto/echo_go_protob\x06proto3"

var (
	file_example_proto_echo_proto_rawDescOnce sync.Once
	file_example_proto_echo_proto_rawDescData []byte
)

func file_example_proto_echo_proto_rawDescGZIP() []byte {
	file_example_proto_echo_proto_rawDescOnce.Do(func() {
		file_example_proto_echo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_example_proto_echo_proto_rawDesc), len(file_example_proto_echo_proto_rawDesc)))
	})
	return file_example_proto_echo_proto_rawDescData
}

var file_example_proto_echo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_example_proto_echo_proto_goTypes = []any{
	(*EchoRequest)(nil),  // 0: s2av2.example.proto.EchoRequest
	(*EchoResponse)(nil), // 1: s2av2.example.proto.EchoResponse
}
var file_example_proto_echo_proto_depIdxs = []int32{
	0, // 0: s2av2.example.proto.Echo.Echo:input_type -> s2av2.example.proto.EchoRequest
	1, // 1: s2av2.example.proto.Echo.Echo:output_type -> s2av2.example.proto.EchoResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_example_proto_echo_proto_init() }
func file_example_proto_echo_proto_init() {
	if File_example_proto_echo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_example_proto_echo_proto_rawDesc), len(file_example_proto_echo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_example_proto_echo_proto_goTypes,
		DependencyIndexes: file_example_proto_echo_proto_depIdxs,
		MessageInfos:      file_example_proto_echo_proto_msgTypes,
	}.Build()
	File_example_proto_echo_proto = out.File
	file_example_proto_echo_proto_goTypes = nil
	file_example_proto_echo_proto_depIdxs = nil
}
